name: On push develop

on:
  push:
    branches:
      - develop
env:
  PROJECT_ID: k8s-skore-dev
  GKE_CLUSTER: k8s-skore-dev
  GKE_ZONE: us-east1-d
  DEPLOYMENT_NAME: skore-ts-template
  IMAGE: skore-ts-template

jobs:
  build_and_deploy:
    name: Build and deploy to staging

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch git history
        run: git fetch --prune --unshallow

      - name: Setup git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY

      - name: Setup Java for sonarqube scanner
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup sonar-scanner
        uses: warchant/setup-sonar-scanner@v3

      - name: NPM cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Dependencies
        run: npm install

      - name: Setup Test Dependencies
        run: |
          docker-compose up -d mongodb redis

      - name: Tests
        run: |
          npm test

      - name: SonarQube
        run: sonar-scanner
          -Dsonar.host.url=##SONARQUBE_URL##
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.login=${{ secrets.SONARQUBE_KEY }}
          -Dsonar.projectKey=${{ github.event.repository.name }}
          -Dsonar.sources=src
          -Dsonar.tests=test
          -Dsonar.cpd.exclusions='**/*.test.ts'
          -Dsonar.test.inclusions='test/**/*.test.ts'
          -Dsonar.coverage.exclusions='**/*index.ts,**/*app.module.ts,**/*.dto.ts,**/*.test.ts'
          -Dsonar.testExecutionReportPaths=coverage/test-reporter.xml
          -Dsonar.branch.name=develop

      - name: Publish release
        run: npx release-it --preRelease=develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve version
        run: echo "RELEASE=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_REGISTRY_DEV }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: gcloud --quiet auth configure-docker

      - name: Build
        run: docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$RELEASE" .

      - name: Publish
        run: docker push "gcr.io/$PROJECT_ID/$IMAGE:$RELEASE"

      - name: Set k8s credentials
        run: echo "${{ secrets.K8S_CREDENTIALS }}" > kube_config

      - name: Deploy application
        run: |-
          sed "s|##IMAGE##|gcr.io/$PROJECT_ID/$IMAGE:$RELEASE|g" .k8s/deployment_web.tpl.yaml | kubectl apply -f -
          kubectl apply -f .k8s/service.yaml
          sed "s|##APP_URL##|skore-ts-template.skore.dev|g" .k8s/nginx-ingress.tpl.yaml | kubectl apply -f -
        env:
          KUBECONFIG: kube_config
